### DEVICE BASE #############################################################
esphome:
  name: esp-weather

esp8266:
  board: d1_mini

ota:
  safe_mode: True

logger:
  level: debug

web_server:

wifi:
  networks:
    - ssid: SAP-Guest
    - ssid: !secret wifi_ssid
      password: !secret wifi_password

